version: '3'
services:

  keelson-interface-docker:
    build: .
    # image: ghcr.io/mo-rise/keelson-interface-docker:latest
    container_name: keelson-interface-docker-0
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - KEELSON_REALM=rise
      - KEELSON_SESSION_ID=seahorse
      - KEELSON_INTERFACE_TYPE=docker-sdk
      - KEELSON_INTERFACE_NAME=sh-1
